TILEWIDTH: int = 16
TILEHEIGHT: int = 16
NROWS: int = 26
NCOLS: int = 36
SCREENWIDTH: int = NCOLS * TILEWIDTH
SCREENHEIGHT: int = NROWS * TILEHEIGHT
SCREENSIZE: tuple[int, int] = (SCREENWIDTH, SCREENHEIGHT)
BLACK: tuple[int, int, int] = (0, 0, 0)
